HOME_ROUTE="/"
LOGIN_ROUTE="/login"
REGISTER_ROUTE="/register"
RESET_PASSWORD_ROUTE="/reset-password"
PROFILE_ROUTE="/profile"
GOOGLE_SIGNIN_ROUTE="/google-signin"
LOGIN_NEEDED_ROUTE="/login-needed"
LOGOUT_NEEDED_ROUTE="/logout-needed"